const sum = require("./sum")
const objectize = require("./objects")
const doString = require("./strings")
const arrays = require("./arrays")
const test_throws = require("./throws")
const fetchData = require("./async_testing/callback")
const promiseFetch = require("./async_testing/promises")
const asyncFetch = require("./async_testing/asyncAwait")
const { multiply, processArray } = require("./mock_functions/withCallback")

console.log(sum(1, 2))
console.log(objectize("a_key", "a_value"))
console.log(doString("Hello there!"))
console.log(arrays("arrays"))
fetchData(console.log)
promiseFetch().then(console.log)
asyncFetch().then(console.log)
console.log(multiply(2, 5))
console.log(processArray([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 70, multiply))

// test_throws.throws()
